Revert "fix for zoxide alias"
This reverts commit 90c69f0dd85a6b99f9df17e18c189ab8197779d1.

diff --git a/dotfiles/zsh/.config/zsh/aliases b/dotfiles/zsh/.config/zsh/aliases
--- a/dotfiles/zsh/.config/zsh/aliases
+++ b/dotfiles/zsh/.config/zsh/aliases
@@ -10,3 +10,18 @@ alias t='tmux attach || tmux new -s Work'
 open() (
   xdg-open "$@" >/dev/null 2>&1 &
 )
+
+if (( $+commands[zoxide] )); then
+  alias cd=zd
+  zd() {
+    if (( $# == 0 )); then
+      builtin cd "$HOME" || return
+    elif [[ -d $1 ]]; then
+      builtin cd "$1" || return
+    elif ! z "$@"; then
+      echo "Directory not found: $*"
+      return 1
+    fi
+    pwd
+  }
+fi
